{
 "title": "logs-tempo",
 "tags": [
  "logs",
  "tempo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "level", "query": "error,warn,info,debug" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Tempo Logs | Level: $level" } },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"tempo\"}"
    }
   ]
  },
  {
   "title": "Spans/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_spans_received_total[5m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"vault-aio\", app=\"tempo\"} |~ \"(?i)error\" [$__range])"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"vault-aio\", app=\"tempo\"} |~ \"(?i)warn\" [$__range])"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"vault-aio\", app=\"tempo\"} |~ \"(?i)($level)\" [$__interval])",
     "legendFormat": "logs"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Tempo Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"vault-aio\", app=\"tempo\"} |~ \"(?i)($level)\""
    }
   ]
  }
 ]
}